export const BLOCKQUOTE = 'blockquote';
export const HEADER = 'header';
// each header type should be start with HEADER, all of justices should based on HEADER
export const HEADER1 = `${HEADER}1`;
export const HEADER2 = `${HEADER}2`;
export const HEADER3 = `${HEADER}3`;
export const HEADER4 = `${HEADER}4`;
export const HEADER5 = `${HEADER}5`;
export const HEADER6 = `${HEADER}6`;
export const ORDERED_LIST = 'ordered_list'; // <ol>
export const UNORDERED_LIST = 'unordered_list'; // <ul> // unordered_list can not work
export const LIST_ITEM = 'list_item'; // <li>
export const CHECK_LIST_ITEM = 'check_list_item';
export const PARAGRAPH = 'paragraph';
export const CODE_BLOCK = 'code_block';
export const CODE_LINE = 'code_line';
export const TABLE = 'table';
export const TABLE_ROW = 'table_row';
export const TABLE_CELL = 'table_cell';
export const IMAGE = 'image';
export const LINK = 'link';
export const FORMULA = 'formula';
export const COLUMN = 'column';
export const LINK_REFERENCE = 'link-reference';
export const DEFINITION = 'definition';
