import * as ELEMENT_TYPE from './element-types';

export const SDOC_FONT_SIZE = {
  DEFAULT: 11,
  [ELEMENT_TYPE.TITLE]: 26,
  [ELEMENT_TYPE.SUBTITLE]: 15,
  [ELEMENT_TYPE.HEADER1]: 20,
  [ELEMENT_TYPE.HEADER2]: 16,
  [ELEMENT_TYPE.HEADER3]: 14,
  [ELEMENT_TYPE.HEADER4]: 12,
  [ELEMENT_TYPE.HEADER5]: 11,
  [ELEMENT_TYPE.HEADER6]: 11,
  [ELEMENT_TYPE.CODE_LINE]: 10,
};
